# Series

In [13]:
import pandas as pd

x=[2,3,4,5,5,6]

var=pd.Series(x,index=['a','b','c','d','e','f'],dtype="float",name="python")
print(var)
print(type(var))
print(var[3])

a    2.0
b    3.0
c    4.0
d    5.0
e    5.0
f    6.0
Name: python, dtype: float64
<class 'pandas.core.series.Series'>
5.0

In [19]:
dic={"Name":['python','c','java','c++'],"por":[12,13,14,15],"rank":[1,4,3,2]}
var1=pd.Series(dic)
print(var1)

s=pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)
print(type(s))

#no broadcasting error in pandas
s1=pd.Series(12,index=[1,2,3,4])
s2=pd.Series(8,index=[0,1,2])
print(s1+s2)

Name    [python, c, java, c++]
por           [12, 13, 14, 15]
rank              [1, 4, 3, 2]
dtype: object
1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64
<class 'pandas.core.series.Series'>
0     NaN
1    20.0
2    20.0
3     NaN
4     NaN
dtype: float64

# DataFrames

In [29]:
#2D data in pandas
l=[1,2,3,4,5,6]
var=pd.DataFrame(l)
print(var)
print(type(var))

d={"a":[1,2,3,4,5],"s":[6,7,8,9,10]}
var1=pd.DataFrame(d)
print(var1)
print(var1["a"][3],var1["s"][2])
print()

var1=pd.DataFrame(d,columns=["a"])
print(var1)

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>
   a   s
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10
4 8

   a
0  1
1  2
2  3
3  4
4  5

In [35]:
list_1=[[1,2,3,4,5],[6,7,8,8,9]]
var2=pd.DataFrame(list_1)
print(type(list_1))
print(var2)
print()

sr={"s":pd.Series([1,2,3,4]),"r":pd.Series([4,5,6,7])}
var3=pd.DataFrame(sr)
print(var3)
print(type(var3))

<class 'list'>
   0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  8  9

   s  r
0  1  4
1  2  5
2  3  6
3  4  7
<class 'pandas.core.frame.DataFrame'>

# Arithmetic Operations in Pandas

In [85]:
var=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})

var

var["C"]=var["A"]+var["B"]
var

var["Python"]=var["C"]<=8
var

   A  B   C  Python
0  1  5   6    True
1  2  6   8    True
2  3  7  10   False
3  4  8  12   False

# Deleting and inserting in pandas

In [95]:
#insert
var =pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
var
var.insert(1,"python",var["B"])
var

   A  python  B
0  1       9  9
1  2       8  8
2  3       7  7
3  4       6  6
4  5       5  5

In [96]:
var.insert(2,"c",[4,5,6,7,8])
var

   A  python  c  B
0  1       9  4  9
1  2       8  5  8
2  3       7  6  7
3  4       6  7  6
4  5       5  8  5

In [ ]:
# Delete
var1=var.pop("B")
var

# Creating CSV File in pandas python

In [103]:
dis={"A":[1,2,3,4,5,6],"B":[7,8,8,9,0,1],"C":[10,11,12,13,14,15]}
data=pd.DataFrame(dis)
print(data)
data.to_csv("Test_new3.csv",index=False,header=False)

   A  B   C
0  1  7  10
1  2  8  11
2  3  8  12
3  4  9  13
4  5  0  14
5  6  1  15

# Reading CSV File

In [134]:
import pandas as pd
csv_1=pd.read_csv("sample.csv")
csv_1

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [162]:
csv_2=pd.read_csv("sample.csv",skiprows=[0,1,2,3,4,5])
csv_2

,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41704,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41705,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41706,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41707,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41708,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [163]:
csv_2=pd.read_csv("sample.csv",index_col="Year")
csv_2

,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
Year,,,,,,,,,
2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...
2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [165]:
csv_2=pd.read_csv("sample.csv",header=2)
csv_2

,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890","ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41708,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41709,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [168]:
csv_2=pd.read_csv("sample.csv",names=["cum1","cum2","cum3","cum4","cum5"])
csv_2

                                                                                                              cum1  \
Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC       Units               Variable_code
2021 Level 1                     99999                All industries             Dollars (millions)            H01
                                                                                 Dollars (millions)            H04
                                                                                 Dollars (millions)            H05
                                                                                 Dollars (millions)            H07
...                                                                                                            ...
2013 Level 3                     ZZ11                 Food product manufacturing Percentage                    H37
                                                                                 Percentage                    H38
                                                                                 Percentage                    H39
                                                                                 Percentage                    H40
                                                                                 Percentage                    H41

                                                                                                                                                cum2  \
Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC       Units                                                 Variable_name
2021 Level 1                     99999                All industries             Dollars (millions)                                     Total income
                                                                                 Dollars (millions)  Sales, government funding, grants and subsidies
                                                                                 Dollars (millions)                Interest, dividends and donations
                                                                                 Dollars (millions)                             Non-operating income
...                                                                                                                                              ...
2013 Level 3                     ZZ11                 Food product manufacturing Percentage                                              Quick ratio
                                                                                 Percentage                      Margin on sales of goods for resale
                                                                                 Percentage                                         Return on equity
                                                                                 Percentage                                   Return on total assets
                                                                                 Percentage                                    Liabilities structure

                                                                                                                      cum3  \
Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC       Units                   Variable_category
2021 Level 1                     99999                All industries             Dollars (millions)  Financial performance
                                                                                 Dollars (millions)  Financial performance
                                                                                 Dollars (millions)  Financial performance
                                                                                 Dollars (millions)  Financial performance
...                                                                                                                    ...
2013 Level 3                     ZZ11                 Food product manufacturing Percentage               Financial ratios
                                                                                 Percentage               Financial ratios
                                                                                 Percentage               Financial ratios
                                                                                 Percentage               Financial ratios
                                                                                 Percentage               Financial ratios

                                                                                                        cum4  \
Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC       Units                 Value
2021 Level 1                     99999                All industries             Dollars (millions)  757,504
                                                                                 Dollars (millions)  674,890
                                                                                 Dollars (millions)   49,593
                                                                                 Dollars (millions)   33,020
...                                                                                                      ...
2013 Level 3                     ZZ11                 Food product manufacturing Percentage               52
                                                                                 Percentage               40
                                                                                 Percentage               12
                                                                                 Percentage                5
                                                                                 Percentage               46

                                                                                                                                                  cum5
Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC       Units                                          Industry_code_ANZSIC06
2021 Level 1                     99999                All industries             Dollars (millions)  ANZSIC06 divisions A-S (excluding classes K633...
                                                                                 Dollars (millions)  ANZSIC06 divisions A-S (excluding classes K633...
                                                                                 Dollars (millions)  ANZSIC06 divisions A-S (excluding classes K633...
                                                                                 Dollars (millions)  ANZSIC06 divisions A-S (excluding classes K633...
...                                                                                                                                                ...
2013 Level 3                     ZZ11                 Food product manufacturing Percentage          ANZSIC06 groups C111, C112, C113, C114, C115, ...
                                                                                 Percentage          ANZSIC06 groups C111, C112, C113, C114, C115, ...
                                                                                 Percentage          ANZSIC06 groups C111, C112, C113, C114, C115, ...
                                                                                 Percentage          ANZSIC06 groups C111, C112, C113, C114, C115, ...
                                                                                 Percentage          ANZSIC06 groups C111, C112, C113, C114, C115, ...

[41716 rows x 5 columns]

# Pandas Fucntions

In [183]:
df=pd.read_csv("sample.csv")
df
df.index

RangeIndex(start=0, stop=41709, step=1)

In [186]:
df=pd.read_csv("sample.csv",nrows=14)
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [191]:
df.index
df.head(10)
df.tail(2)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [196]:
df[4:10]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...

In [198]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [201]:
df.index.array

<PandasArray>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
Length: 14, dtype: int64

In [204]:
df.to_numpy()

array([[2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H01', 'Total income', 'Financial performance', '757,504',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H04', 'Sales, government funding, grants and subsidies',
        'Financial performance', '674,890',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H05', 'Interest, dividends and donations',
        'Financial performance', '49,593',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H07', 'Non-operating income', 'Financial performance', '33,020',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H08', 'Total expenditure', 'Financial performance', '654,404',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H09', 'Interest and donations', 'Financial performance',
        '26,138',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H10', 'Indirect taxes', 'Financial performance', '6,991',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H11', 'Depreciation', 'Financial performance', '27,801',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H12', 'Salaries and wages paid', 'Financial performance',
        '123,620',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H13', 'Redundancy and severance', 'Financial performance',
        '275',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H14', 'Salaries and wages to self employed commission agents',
        'Financial performance', '2,085',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H19', 'Purchases and other operating expenses',
        'Financial performance', '452,963',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H20', 'Non-operating expenses', 'Financial performance',
        '14,806',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2021, 'Level 1', 99999, 'All industries', 'Dollars (millions)',
        'H21', 'Opening stocks', 'Financial performance', '68,896',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)']],
      dtype=object)

In [207]:
df.sort_index(axis=0,ascending=False)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...

In [211]:
df["Industry_code_NZSIOC"][0]="99000"
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99000,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [215]:
df.loc[6,"Industry_code_NZSIOC"]="1001"
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99000,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,1001,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [216]:
df.loc[[2,3],["Industry_code_NZSIOC"]]

  Industry_code_NZSIOC
2                99999
3                99999

In [222]:
df.iloc[2,2]

99999

In [224]:
df.drop("Industry_code_NZSIOC",axis=1)

,Year,Industry_aggregation_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [227]:
df.drop(0,axis=0)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,1001,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

# Drop NaN and fil NaN

In [229]:
dfc=pd.read_csv("sample.csv",nrows=14)
dfc

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [234]:
dfc.dropna(axis=0) #asix=0 for along row and 1 for along column

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [236]:
dfc

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [238]:
dfc.dropna(how="any")

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [246]:
dfc

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [250]:
dfc.dropna(inplace=True)
dfc

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [253]:
dfca=pd.read_csv("sample.csv",nrows=14)
dfca

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [259]:
dfca.dropna(thresh=1) #removes the no of rows with 1 null values

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [261]:
#Fillna

In [264]:
dfca.fillna({"Industry_code_NZSIOC":"python","Variable_code":"java"})#filling a null value

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,python,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),java,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,python,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,python,All industries,Dollars (millions),java,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [265]:
dfca

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [266]:
dfca.fillna(method="ffill") #forward filling from previous row

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999.0,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,99999.0,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [268]:
dfca.fillna(method='bfill',axis=1)#backward filling from left data

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,All industries,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),Indirect taxes,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,All industries,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,All industries,All industries,Dollars (millions),Non-operating expenses,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [271]:
dfca.fillna(12,inplace=True)
dfca

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,12.0,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),12,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,12.0,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,12.0,All industries,Dollars (millions),12,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [275]:
dfcaf=pd.read_csv("sample.csv",nrows=14)
dfcaf

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,NaN,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),NaN,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,NaN,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),NaN,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...

In [276]:
dfcaf.fillna("python",limit=2)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,python,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021,Level 1,99999.0,All industries,Dollars (millions),python,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021,Level 1,python,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"123,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,NaN,All industries,Dollars (millions),python,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...